name: Laravel CD

on:
    workflow_run: 
        workflows: ["Laravel Integration"]
        types:
            - completed

jobs:
    publish:
        runs-on: self-hosted
        steps:
            - name: Docker login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Pull the docker image
              run: docker pull tanvirasifkhan/laravel-app:latest
            - name: Delete old running container
              run: docker rm -f laravel-app || true
            - name: Run container from pulled image
              run: docker run --name laravela-app -p 8000:8000 -d tanvirasifkhan/laravel-app
            